name: .NET Core

on: [push]

jobs:
  build:

    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Build with dotnet
      run: dotnet publish --configuration Release

    - name: Test with dotnet
      run: dotnet test 
      
    - name: Publish Release
      uses: fnkr/github-action-ghr@v1.2
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_PATH: src/Cmf.Tools.TestDetector.Console/bin/Release/netcoreapp3.1/publish
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
